### PR TITLE
Gmao/hirs2 noaa14

### LINKED ISSUE #23: [bug] hirs2 noaa 14
HIRS2 on noaa 14 is turned off prematurely on [1995050100](https://github.com/jswhit/build_gsinfo/blob/master/satinfo/hirs2_n14/1995050100). Shold be off as in readme file on 20060930

### PR DESCRIPTION
**Pull request by frolovsa**
closes #23

### CODE REVIEW

**Comment by jswhit** [comment]
I don't believe NCEP is using hirs4 from metop-b and I think this is why I left it off.  I'll double check.

**Comment by jswhit** [comment]
This PR shouldn't have the hirs4 and sndr_g13 parts in it?

**Comment by frolovsa** [comment]
I will remove hirs4 and sndr_g13 from this PR.

**Comment by frolovsa** [comment]
@jswhit this is a clean PR now, hirs4 and sndr_g13 are removed

**Pull request merged**
