### PR TITLE
GMAO atms

### PR DESCRIPTION
**Pull request by jswhit**

### CODE REVIEW

**Review by frolovsa — CHANGES_REQUESTED** [review]
do you also need to remove file 
[2018053012](https://github.com/jswhit/build_gsinfo/blob/master/satinfo/atms_n20/2018053012)

**Comment by jswhit** [comment]
> do you also need to remove file [2018053012](https://github.com/jswhit/build_gsinfo/blob/master/satinfo/atms_n20/2018053012)

It was a git rename.

**Comment by frolovsa** [comment]
@jswhit i still see [2018053012](https://github.com/jswhit/build_gsinfo/blob/master/satinfo/atms_n20/2018053012) in the GMAOatms branch. I dont think it was removed properly. I might be wrong though.

**Comment by jswhit** [comment]
that file is really removed now

**Pull request merged**
