### PR TITLE
GMAO ssmi

### PR DESCRIPTION
**Pull request by jswhit**

### CODE REVIEW

**Review by frolovsa — COMMENTED** [review]
Jeff @jswhit what datastream (filename) do i need to copy to support your more aggressive use of ssmi/smmis radiance data.

**Comment by jswhit** [comment]
> Jeff @jswhit what datastream (filename) do i need to copy to support your more aggressive use of ssmi/smmis radiance data.

That's a good question - I don't know

**Comment by jswhit** [comment]
looking at the GSI scripts, ssmit has ssmi_f14 and ssmi_f15.  ssmis has  ssmis_f16.  Not sure what else is in the archive with 'ssmi' in the filename.

**Comment by jswhit** [comment]
From the NCEP documentation, I found
ssmisu bufr contains DMSP F-16, F-17 and F-18 SSM/IS UPP 1B brightness temperatures, starting 2009?
ssmit also contains brightness temperatures (not sure how different than ssmisu)
ssmipn and spssmi contains SSMI products (rain rate, wind, not radiances)

Don't think we have any of the older ssmi data, will have to rely on NASA or reprocessed data from Jack

**Review by frolovsa — APPROVED** [review]
I think we can merge this. We have repro files from jack now. We can revise this later also to include all sky channels.

**Pull request merged**
